name: mbti

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  wedding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: instaill dependencies
        run: npm install

      - name: Check eslint
        run: npm lint
